username_field = '//*[@id="user-name"]'
password_field = '//*[@id="password"]'
login_button = '//*[@id="login-button"]'
auth_error = '//h3[contains(@data-test, "error")]'
add_backpack_to_cart = '//*[@id="add-to-cart-sauce-labs-backpack"]'
remove_backpack_from_cart = '//*[@id="remove-sauce-labs-backpack"]'
shopping_cart = '//*[@id="shopping_cart_container"]'
add_item_to_cart_in_card = "add-to-cart"
remove_item_from_cart_in_card = "remove"
item_picture = '//*[@id="item_4_img_link"]'
item_title = '//*[@id="item_4_title_link"]/div'
first_name_field = '//*[@id="first-name"]'
last_name_field = '//*[@id="last-name"]'
postal_code_field = '//*[@id="postal-code"]'
checkout_button = '//*[@id="checkout"]'
continue_button = '//*[@id="continue"]'
finish_button = '//*[@id="finish"]'
filter_A_to_Z ='//*[@id="header_container"]/div[2]/div/span/select/option[1]'
filter_Z_to_A = '//*[@id="header_container"]/div[2]/div/span/select/option[2]'
filter_low_to_high = '//*[@id="header_container"]/div[2]/div/span/select/option[3]'
filter_high_to_low = '//*[@id="header_container"]/div[2]/div/span/select/option[4]'
inventory_item_name = '//*[@data-test="inventory-item-name"]'
inventory_item_price ='//*[@data-test="inventory-item-price"]'
burger_menu = '//*[@id="react-burger-menu-btn"]'